name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package latest app code into zip
        run: zip -j local.zip python/main.py

      - name: Reconcile target environment
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          [[ $BRANCH = "main" ]] && WORKSPACE="default" || WORKSPACE=$BRANCH
          echo workspace: $WORKSPACE
          export TF_VAR_workspace=$WORKSPACE
          cd terraform
          terraform init
          terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
          terraform apply -auto-approve
          echo $(terraform output -json | jq '.infra.value | join(" url: ")') >> $GITHUB_STEP_SUMMARY
        env:
          AWS_DEFAULT_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
